# Generated by Django 3.0.5 on 2020-05-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='dia',
            new_name='data',
        ),
    ]
