# Generated by Django 3.0.6 on 2020-05-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20200527_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['data'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['horario']},
        ),
        migrations.AlterField(
            model_name='horario',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agenda.Agenda'),
        ),
    ]
